config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  resources :phrases, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :authors, only: [:index, :new, :create]
  resources :books, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :phrases
  
  validates :name, presence: true, length: { maximum: 255 }
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :content, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :phrases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end    
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_user_logged_in

  def index
    @authors = Author.order(id: :desc).page(params[:page]).per(25)
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    
    if @author.save
      flash[:success] = '著者が登録できました'
      redirect_to new_book_path(author_id: @author.id)
    else
      flash[:danger] = '登録できませんでした'
      render :new
    end
  end
  
  private
  
  def author_params
    params.require(:author).permit(:name)
  end
    
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @books = Book.all.includes(:phrases)
  end

  def new
    @book = Book.new
    # params[:author_id]
  end

  def create
    @book = Book.new(book_params)
    @book.author_id = params[:author_id]
    
    if @book.save
      flash[:success] = '本の登録ができました'
      redirect_to new_phrase_path(book_id: @book.id)
    else
      flash[:danger] = '登録できませんでした'
      render :new
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:name)
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_phrase, only: [:show, :edit, :update, :destroy] 
  
  
  def new
    @phrase = Phrase.new
  end

  def create
    @phrase = Phrase.new(phrase_params)
    @phrase.book_id = params[:book_id]
    @phrase.user_id = current_user.id
    
    if @phrase.save
      flash[:success] = 'フレーズを投稿しました'
      redirect_to root_url
    else
      flash[:danger] = '投稿できませんでした'
      render :new
    end
  end

  def show
    @book = @phrase.book
    @author = @book.author
  end

  def edit
  end

  def update
    
    if @phrase.update(phrase_params)
      flash[:success] = 'フレーズを更新しました'
      redirect_to @phrase
    else
      flash[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    
    if @phrase.destroy
      flash[:success] = 'フレーズを削除しました'
      redirect_to root_url
    end
  end
  
  private
  
  def phrase_params
    params.require(:phrase).permit(:content, :comment)
  end
  
  def set_phrase
    @phrase = Phrase.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash[:danger] = 'ログインできませんでした'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @phrases = current_user.phrases.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).includes(:phrases).per(25)
  end

  def show
    @user = User.find(params[:id])
    @phrases = @user.phrases.order(id: :desc).page(params[:page]).per(25)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザ登録完了しました'
      redirect_to @user
    else
      flash[:danger] = '登録できませんでした'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/authors/index.html.erb
<div class="row">
  <div class="text-center">
    <h2>著者一覧</h2>
  </div>
  <table class="table table-striped">
    <tr>
      <th>著者名</th>
      <th>投稿された最新書籍</th>
    </tr>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.books.present? ? author.books.last.name : '書籍は投稿されてません' %></td>
      </tr>
    <% end %>
  </table>
  
  
  <!--% @authors.select{|author| author.books.present? }.each do |author| %-->
    
</div>

app/views/authors/new.html.erb
<div class="row">
  <div class="text-center mb-5 col-sm-12">
    <h2>フレーズを残そう！</h2>
  </div>
  <aside class="col-sm-6">
    <%= form_with(url: new_book_path, local: true, method: :get) do |f| %>
      <%= label_tag :author_id, '著者名' %>
      <%= select_tag :author_id, options_for_select(Author.all.map{ |author| [author.name, author.id] }) %>
      <%= f.submit '作品名入力へ', class: 'col-sm-3 offset-sm-3 btn btn-primary btn-block' %>
    <% end %>
    
    <!-- %= select_tag :author_id, options_from_collection_for_select(Author.all, :id, :name) %-->
  </aside>
  <div class="col-sm-6">
    <%= form_with(model: @author, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, '著者一覧にない場合はこちらを入力' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <%= f.submit '作品名入力へ', class: 'col-sm-3 offset-sm-3 btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="row">
  <div class="text-center">
    <h2>作品名一覧</h2>
  </div>
  <table class="table table-striped">
    <tr>
      <th>作品名</th>
      <th>著者名</th>
      <th>最新フレーズ</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author.name %></td>
        <td><%= book.phrases.present? ? book.phrases.last.content : 'フレーズはありません' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<div class="row">
  <div class="text-center mb-5 col-sm-12">
    <h2>フレーズを残そう！</h2>
  </div>
  <aside class="col-sm-6">
    <%= form_with(url: new_phrase_path, local: true, method: :get) do |f| %>
      <%= hidden_field_tag :author_id, params[:author_id] %>
      <%= label_tag :book_id, '書籍名' %>
      <%= select_tag :book_id, options_for_select(Book.where(author_id: params[:author_id]).map{ |book| [book.name, book.id] }) %>
      <%= f.submit 'フレーズ入力へ', class: 'col-sm-3 offset-sm-3 btn btn-primary btn-block' %>
    <% end %>
    <!--%= select_tag :book_id, options_from_collection_for_select(Book.all, :id, :name) %-->
  </aside>
  <div class="col-sm-6">
    <%= form_with(model: @book, local: true) do |f| %>
      <div class="form-group">
        <%= hidden_field_tag :author_id, params[:author_id] %>
        <%= f.label :name, '作品一覧にない場合はこちらを入力' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <%= f.submit 'フレーズ入力へ', class: 'col-sm-3 offset-sm-3 btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-black" href="/">One Phrase</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportContent">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '書籍一覧', books_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '著者一覧', authors_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Phrases</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/phrases/edit.html.erb
<div class="row">
  <div class="text-center mb-5">
    <h2>フレーズを修正する</h2>
  </div>
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @phrase, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :content, 'フレーズ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="form-group">  
        <%= f.label :comment, 'コメント' %>
        <%= f.text_field :comment, class: 'form-control' %>
      </div>
      <%= f.submit 'フレーズ修正', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/phrases/new.html.erb
<div class="row">
  <div class="text-center mb-5 col-sm-12">
    <h2>フレーズを残そう！</h2>
  </div>
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @phrase, local: true) do |f| %>
      <!--%= hidden_field_tag :book_id, params[:book_id] %-->
      <!--%= hidden_field_tag :user_id, current_user.id %-->
      <div class="form-group">
        <%= hidden_field_tag :book_id, params[:book_id] %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= f.label :content, 'フレーズ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= hidden_field_tag :book_id, params[:book_id] %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= f.label :comment, 'コメント' %>
        <%= f.text_field :comment, class: 'form-control' %>
      </div>
      <%= f.submit 'フレーズ投稿', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/phrases/show.html.erb
<div class="row">
  <div class="text-center mb-5">
    <h2>フレーズ詳細</h2>
  </div>
  <div class="col-sm-12">
    <h5>著者名</h5>
    <p><%= @author.name %></p>
  </div>
  <div class="col-sm-12">
    <h5>作品名</h5>
    <p><%= @book.name %></p>
  </div>
  <div class="col-sm-12">
    <h5>フレーズ</h5>
    <p><%= @phrase.content %></p>
  </div>
  <div class="col-sm-12">
    <h5>コメント</h5>
    <p><%= @phrase.comment %></p>
  </div>
  <div class="col-sm-12">
    <%= link_to 'フレーズ修正', edit_phrase_path(@phrase) %>
  </div>
  <div class="col-sm-12">
    <%= link_to 'フレーズを消去する', @phrase, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }  %>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <h2 class="text-center mb-4">あなたが残したフレーズ</h2>
  <table class="table table-striped">
    <tr>
      <th class="text-center">フレーズ</th>
      <th class="text-center">作品名</th>
      <th class="text-center">投稿日時</th>
    </tr>
    <% @phrases.each do |phrase| %>
      <tr>
        <td class="text-center"><%= link_to phrase.content, phrase_path(phrase) %></td>
        <td class="text-center"><%= phrase.book.name %></td>
        <td class="text-center"><%= phrase.created_at.strftime("%Y-%m-%d%H:%M")  %></td>
      </tr>
    <% end %>
  </table>
  <div class="mt-3 col-sm-4 offset-sm-4">
    <%= link_to '新規フレーズ投稿', new_author_url, class: 'btn btn-block btn-primary' %>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>One Phrase</h1>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded border border-primary" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= link_to user.name, user_path(user) %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :password_confirmation, 'パスワード再確認' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        
        <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  
  <div class="card offset-sm-4 mb-4">
    <div class="card-body">
      <h2><%= @user.name %>の「フレーズ」</h2>
    </div>
  </div>
  
  <table class="table table-striped">
    <tr>
      <th class="text-center">フレーズ</th>
      <th class="text-center">作品名</th>
      <th class="text-center">投稿日時</th>
    </tr>
    <% @phrases.each do |phrase| %>
      <tr>
        <td class="text-center"><%= phrase.content %></td>
        <td class="text-center"><%= phrase.book.name %></td>
        <td class="text-center"><%= phrase.created_at %></td>
      </tr>
    <% end %> 
  </table>
</div>